config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :funcionarios
  resources :planos, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
  belongs_to :user
  has_many :planos, through: :user

  validates :name, :email, :cpf, :data_admissao, :peso, :altura, :endereco, :horas_meditadas, presence: true

end

app/models/plano.rb
class Plano < ApplicationRecord
  belongs_to :user
  has_many :funcionarios, through: :user

  validates :nome, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :funcionarios, dependent: :destroy
  has_many :planos, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_devise_params, if: :devise_controller?

  def configure_devise_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :authenticate_user!
  before_action :find_funcionario, only: %i[edit update show destroy]

  def index
    @funcionarios = Funcionario.where(user: current_user)
    @planos = Plano.where(user: current_user)
  end

  def show;end

  def new
    @funcionario = Funcionario.new
  end

  def create
    @funcionario = Funcionario.new(funcionario_params)
    @funcionario.user = current_user
    if @funcionario.save
      redirect_to funcionarios_path, notice: "Funcionário adicionado com sucesso!"
    else
      render :new
    end
  end

  def edit;end

  def update
    if @funcionario.update(funcionario_params)
      redirect_to funcionarios_path, notice: 'Dados atualizados!'
    else
      render :edit
    end
  end

  def destroy
    @funcionario.destroy
    redirect_to funcionarios_path
  end

  private

  def find_funcionario
    @funcionario = Funcionario.find(params[:id])
  end

  def funcionario_params
    params.require(:funcionario).permit(:name, :cpf, :email, :data_admissao, :horas_meditadas, :endereco, :peso, :altura)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @planos = Plano.where(user: current_user)
  end
end

app/controllers/planos_controller.rb
class PlanosController < ApplicationController
  def index
    @planos = Plano.where(user: current_user)
  end

  def show
    @plano = Plano.find(params[:id])
    @funcionarios = Funcionario.where(user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/planos_helper.rb
module PlanosHelper
end

app/views/compartilhado/_navbar.html.erb
<nav class="navbar bg-light">
    <%= link_to root_path, class: "navbar-brand" do %>
      <div>
        <h2><i class="fas fa-heartbeat"></i>AppSaúde</h2>
      </div>
    <% end %>

      <div class="nav-link text-reset">
        <% if user_signed_in? %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "text-muted" %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "text-muted" %>
        <% end %>
      </div>
</nav>

app/views/funcionarios/_form.html.erb
<div class='row justify-content-center'>
  <%= simple_form_for [ @funcionario ] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <div class='row mt-2 justify-content-center'>
        <div class="text-left mr-5">
          <%= f.label :name, 'Nome' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="text-left ml-5">
          <%= f.label :cpf, 'CPF' %>
          <%= f.number_field :cpf, class: 'form-control' %>
        </div>
      </div>
      <div class='row mt-5 justify-content-center'>
        <div class="text-left mr-5">
          <%= f.label :email %>
          <%= f.email_field :email, autocomplete: 'email', class: 'form-control' %>
        </div>
        <div class="text-left ml-5">
          <%= f.label :data_admissao, 'Data de Admissão' %>
          <%= f.date_field :data_admissao, autofocus: true, autocomplete: 'email', class: 'form-control' %>
        </div>
      </div>
      <div class='row mt-5 justify-content-center'>
        <div class="text-left mr-5">
          <%= f.label :peso, 'Peso (Kg)' %>
          <%= f.number_field :peso, autofocus: true, autocomplete: 'email', class: 'form-control' %>
        </div>
        <div class="text-left ml-5">
          <%= f.label :altura, 'Altura (cm)' %>
          <%= f.number_field :altura, autofocus: true, autocomplete: 'email', class: 'form-control' %>
        </div>
      </div>
      <div class='row mt-5 justify-content-center'>
        <div class="text-left mr-5">
          <%= f.label :horas_meditadas, 'Horas Meditadas (Últimos 7 dias)' %>
          <%= f.number_field :horas_meditadas, class: 'form-control' %>
        </div>
        <div class="text-left">
          <%= f.label :endereco, 'Endereço' %>
          <%= f.text_field :endereco, autocomplete: 'endereco', class: 'form-control' %>
        </div>
      </div>
      <div class='row mt-2 justify-content-center'>
        <div class="text-left">
          <%= f.hidden_field :user, value: current_user %>
        </div>
      </div>
      <div class='d-flex justify-content-center mt-5' >
        <%= link_to "Back", funcionarios_path, class: "btn btn-home" %>
        <%= f.submit "Cadastrar", class: "btn btn-home mx-3" %>
      </div>
  <% end %>
</div>

app/views/funcionarios/_formacme.html.erb
<div class='row justify-content-center'>
  <%= simple_form_for [ @funcionario ] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <div class='row mt-2 justify-content-center'>
        <div class="text-left mr-5">
          <%= f.label :name, 'Nome' %>
          <%= f.text_field :name, autofocus: true, autocomplete: 'nome', class: 'form-control' %>
        </div>
        <div class="text-left ml-5">
          <%= f.label :cpf, 'CPF' %>
          <%= f.number_field :cpf, autofocus: true, autocomplete: 'cpf', class: 'form-control' %>
        </div>
      </div>
      <div class='row mt-5 justify-content-center'>
        <div class="text-left mr-5">
          <%= f.label :email %>
          <%= f.email_field :email, autofocus: true, autocomplete: 'email', class: 'form-control' %>
        </div>
        <div class="text-left ml-5">
          <%= f.label :data_admissao, 'Data de Admissão' %>
          <%= f.date_field :data_admissao, autofocus: true, autocomplete: 'email', class: 'form-control' %>
        </div>
      </div>
      <div class='row mt-5 justify-content-center'>
        <div class="text-left mr-5">
          <%= f.label :peso, 'Peso (Kg)' %>
          <%= f.number_field :peso, autofocus: true, autocomplete: 'email', class: 'form-control' %>
        </div>
        <div class="text-left ml-5">
          <%= f.label :altura, 'Altura (cm)' %>
          <%= f.number_field :altura, autofocus: true, autocomplete: 'email', class: 'form-control' %>
        </div>
      </div>
      <div class='row mt-2 justify-content-center'>
        <div class="text-left">
          <%= f.hidden_field :user, value: current_user %>
          <%= f.hidden_field :horas_meditadas, value: 'N/A'%>
          <%= f.hidden_field :endereco, value: 'N/A'%>
        </div>
      </div>
      <div class='d-flex justify-content-center mt-5' >
        <%= link_to "Back", funcionarios_path, class: "btn btn-home" %>
        <%= f.submit "Cadastrar", class: "btn btn-home mx-4" %>
      </div>
  <% end %>
</div>

app/views/funcionarios/_formtiopat.html.erb
<div class='row justify-content-center'>
  <%= simple_form_for [ @funcionario ] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <div class='row mt-2 justify-content-center'>
        <div class="text-left mr-5">
          <%= f.label :name, 'Nome' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="text-left ml-5">
          <%= f.label :data_admissao, 'Data de Admissão' %>
          <%= f.date_field :data_admissao, class: 'form-control' %>
        </div>
      </div>
      <div class='row mt-5 justify-content-center'>
        <div class="text-left mr-5">
          <%= f.label :peso, 'Peso (Kg)' %>
          <%= f.number_field :peso, class: 'form-control' %>
        </div>
        <div class="text-left ml-5">
          <%= f.label :altura, 'Altura (cm)' %>
          <%= f.number_field :altura, class: 'form-control' %>
        </div>
      </div>
      <div class='row mt-5 justify-content-center'>
        <div class="text-left">
          <%= f.label :cpf, 'CPF' %>
          <%= f.number_field :cpf, class: 'form-control' %>
        </div>
        <div class="text-left ml-5">
          <%= f.label :horas_meditadas, 'Horas Meditadas (Últimos 7 dias)' %>
          <%= f.number_field :horas_meditadas, class: 'form-control' %>
        </div>
      </div>

      <div class='mt-5 '>
        <div class="text-left">
          <%= f.label :endereco, 'Endereço' %>
          <%= f.text_field :endereco, autocomplete: 'endereco', class: 'form-control' %>
        </div>
      </div>
      <div class='row mt-2 justify-content-center'>
        <div class="text-left">
          <%= f.hidden_field :user, value: current_user %>
          <%= f.hidden_field :email, value: 'N/A' %>
        </div>
      </div>
      <div class='d-flex justify-content-center mt-5' >
        <%= link_to "Back", funcionarios_path, class: "btn btn-home" %>
        <%= f.submit "Cadastrar", class: "btn btn-home mx-3" %>
      </div>
  <% end %>
</div>

app/views/funcionarios/edit.html.erb
<div class = 'container-home' align='center'>
  <div class='text-center py-5'>
      <h1>Atualize cadastro de <%=@funcionario.name%></h1>
  </div>
  <div class="card-form p-5 ">
    <h1 class='text-center'>Ficha: </h1>
    <% if current_user.nickname == 'Tio Patinhas Bank'%>
      <%= render 'formtiopat', funcionario: @funcionario %>
    <% elsif current_user.nickname == 'Acme Co.'%>
      <%= render 'formacme', funcionario: @funcionario %>
    <% else %>
      <%= render 'form', funcionario: @funcionario %>
    <%end%>
  </div>
</div>

app/views/funcionarios/index.html.erb
<div class= "text-center container-home">
  <h1 class= "p-5"> Funcionários </h1>

  <div class= "d-flex p-5 text-center">
    <table class="table">
      <thead class="thead">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Nome</th>
          <th scope="col">CPF</th>
          <th scope="col">Benefícios</th>
          <th scope="col">Empresa</th>
        </tr>
      </thead>
      <tbody >
          <% @funcionarios.each do |funcionario| %>
            <tr>
              <th scope="row"><%= funcionario.id%></th>
              <td><%= link_to funcionario_path(funcionario), id: "text-name-index" do%>
                    <%=funcionario.name.capitalize%>
                  <% end %>
              </td>
              <td><%= funcionario.cpf %></td>
              <td>
                <% funcionario.planos.each do |plano|%>
                  <p><%= plano.nome.capitalize %></p>
                <%end%>
              </td>
              <td><%= funcionario.user.nickname.capitalize %></td>
              <td>
                <%= link_to edit_funcionario_path(funcionario), class: "edit_link" do %>
                  <i class="far fa-edit text-info"></i>
                <% end %>
                <%= link_to  funcionario_path(funcionario), method: :delete, data: { confirm: 'Are you sure?' }, class: "delete_link" do %>
                  <i class="fas fa-trash-alt text-danger"></i>
                <% end %>
              </td>
            </tr>
          <%end%>
      </tbody>
    </table>
  </div>
  <div class= "p-3">
    <%= link_to 'New', new_funcionario_path , class: 'btn-func' %>
    <%= link_to 'Go Back', :back, class: 'mx-3 btn-func' %>
  </div>
</div>

app/views/funcionarios/new.html.erb
<div class = 'container-home' align='center'>
  <div class='text-center py-5'>
      <h1>Cadastre um novo Funcionário</h1>
  </div>
  <div class="card-form p-5 ">
    <h1 class='text-center'>Ficha: </h1>
        <% if current_user.nickname == 'Tio Patinhas Bank'%>
          <%= render 'formtiopat', funcionario: @funcionario %>
        <% elsif current_user.nickname == 'Acme Co.'%>
          <%= render 'formacme', funcionario: @funcionario %>
        <% else %>
          <%= render 'form', funcionario: @funcionario %>
        <%end%>
  </div>
</div>

app/views/funcionarios/show.html.erb
<div class= "container-home" align="center">
    <div class='text-center py-5'>
        <h1>Ficha Completa:</h1>
    </div>
    <div class="card-funcionarios p-5">
      <h2 class= "text-center text-func font-weight-bold">Informações de <%=@funcionario.name%></h2>
      <div class='row'>
        <div class='pl-5 text-left'>
          <div class='d-flex mt-5'>
            <h5>Nome:  </h5>
            <h5 class= "ml-2 text-func"><%=@funcionario.name.capitalize %></h5>
          </div>
          <div class='d-flex mt-3'>
            <h5>CPF:  </h5>
            <h5 class= "ml-2 text-func"><%=@funcionario.cpf %></h5>
          </div>
          <div class='d-flex mt-3'>
            <h5>Email:</h5>
            <h5 class= "ml-2 text-func"><%=@funcionario.email %></h5>
          </div>
          <div class='d-flex mt-3'>
            <h5>Peso:</h5>
            <h5 class= "ml-2 text-func"><%=@funcionario.peso %>Kg</h5>
          </div>
          <div class='d-flex mt-3'>
            <h5>Altura:</h5>
            <h5 class= "ml-2 text-func"><%=@funcionario.altura%>cm</h5>
          </div>
          <div class='d-flex mt-3'>
            <h5>Horas meditadas (Últimos 7 dias):</h5>
            <h5 class= "ml-2 text-func"><%=@funcionario.horas_meditadas %></h5>
          </div>
          <div class='d-flex mt-3'>
            <h5>Endereço:</h5>
            <h5 class= "ml-2 text-func"><%=@funcionario.endereco.capitalize %></h5>
          </div>
          <div class='d-flex mt-3'>
            <h5>Data de Admissão:</h5>
            <h5 class= "ml-2 text-func"><%=@funcionario.data_admissao %></h5>
          </div>
          <div class='d-flex mt-3'>
            <h5>Empresa:</h5>
            <h5 class= "ml-2 text-func"><%=@funcionario.user.nickname %></h5>
          </div>
        </div>
      </div>
      <div class="d-flex justify-content-center pt-5">
        <%= link_to 'Back', funcionarios_path, class: 'btn btn-home ml-3' %>
      </div>
      <div class="pt-5">
        <h5 id="text-data">Criado em  <%= time_tag(@funcionario.created_at) %></h5>
      </div>
    </div>
</div>

app/views/home/index.html.erb
<div class='d-flex flex-column container-home'>
    <div class='text-center p-5'>
      <h1> Olá, <%= current_user.nickname%> </h1>
    </div>
  <div class="card p-5 ">
    <div class='text-center'>
      <h3> O que deseja acessar hoje: </h3>
    </div>
    <div class= 'd-flex justify-content-around' id= 'btn-home-container'>
       <h3><%= link_to 'Benefícios', planos_path, class: "btn-home text-decoration-none" %></h3>
       <h3><%= link_to 'Funcionários', funcionarios_path, class: "btn-home text-decoration-none" %></h3>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PipoChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200&family=Poppins:wght@200;300;500&family=Raleway:wght@200&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "compartilhado/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/planos/index.html.erb
<div class='d-flex flex-column container-home'>
  <div class='text-center p-5'>
    <h1><%= current_user.nickname%> </h1>
  </div>
  <div class="card p-5 justify-content-between ">
    <div class='text-center'>
      <h2> Meus Benefícios contratados: </h2>
    </div>
    <div class='planos-container'>
      <% @planos.each do |plano| %>
       <h4 class='m-2'><i class="fas fa-hand-point-right mr-3 text-info"></i><%= link_to plano.nome, plano_path(plano), class: "planos-name text-decoration-none" %></h4>
      <%end%>
    </div>
    <div class='d-flex justify-content-around btn-planos'>
      <h5><%= link_to 'Back', root_path, class: "btn-home" %></h5>
      <h5><%= link_to 'Adicionar novo benefício', '', class: "btn-home " %></h5>
    </div>
  </div>
</div>

app/views/planos/show.html.erb
<div class= "text-center container-home">
    <h1 class= "p-5"> Funcionários beneficiados na <%= @plano.nome %>:</h1>
    <%if @plano.nome == 'Dental Sorriso'%>
      <div class= "d-flex p-5 text-center">
        <table class="table">
          <thead class="thead">
            <tr>
              <th scope="col">Nome</th>
              <th scope="col">CPF</th>
              <th scope="col">Peso (Kg)</th>
              <th scope="col">Altura (cm)</th>
            </tr>
          </thead>
          <tbody>
              <% @funcionarios.each do |funcionario| %>
                <tr>
                  <td><%=  funcionario.name %></td>
                  <td><%=  funcionario.cpf %></td>
                  <td><%= funcionario.peso %></td>
                  <td><%= funcionario.altura %></td>
                </tr>
              <%end%>
          </tbody>
        </table>
      </div>
    <%end%>
    <%if @plano.nome == 'Pampulha Intermédica'%>
      <div class= "d-flex p-5 text-center">
        <table class="table">
          <thead class="thead">
            <tr>
              <th scope="col">Nome</th>
              <th scope="col">CPF</th>
              <th scope="col">Data Admissão</th>
              <th scope="col">Endereço</th>
            </tr>
          </thead>
          <tbody>
              <% @funcionarios.each do |funcionario| %>
                <tr>
                  <td><%=  funcionario.name %></td>
                  <td><%=  funcionario.cpf %></td>
                  <td><%= funcionario.data_admissao %></td>
                  <td><%= funcionario.endereco %></td>
                </tr>
              <%end%>
          </tbody>
        </table>
      </div>
    <%end%>
    <%if @plano.nome == 'Norte Europa'%>
      <div class= "d-flex p-5 text-center">
        <table class="table">
          <thead class="thead">
            <tr>
              <th scope="col">Nome</th>
              <th scope="col">CPF</th>
              <th scope="col">Data Admissão</th>
              <th scope="col">Email</th>
            </tr>
          </thead>
          <tbody>
              <% @funcionarios.each do |funcionario| %>
                <tr>
                  <td><%=  funcionario.name %></td>
                  <td><%=  funcionario.cpf %></td>
                  <td><%= funcionario.data_admissao %></td>
                  <td><%= funcionario.email %></td>
                </tr>
              <%end%>
          </tbody>
        </table>
      </div>
    <%end%>
    <%if @plano.nome == 'Mente Sã, Corpo São'%>
      <div class= "d-flex p-5 text-center">
        <table class="table">
          <thead class="thead">
            <tr>
              <th scope="col">CPF</th>
              <th scope="col">Horas meditadas nos últimos 7 dias</th>
            </tr>
          </thead>
          <tbody>
              <% @funcionarios.each do |funcionario| %>
                <tr>
                  <td><%=  funcionario.cpf %></td>
                  <td><%= funcionario.horas_meditadas %></td>
                </tr>
              <%end%>
          </tbody>
        </table>
      </div>
    <%end%>
    <div class="d-flex justify-content-center pt-5">
      <%= link_to 'Back', planos_path, class: 'btn btn-home ml-3' %>
    </div>
</div>